#Log config
logging:
  config: classpath:log4j2-dev.xml

spring:
  aop:
    proxy-target-class: true
  #boot:
    #admin:
     # url: http://localhost:58080/admin
      #client:
        #name: ${spring.application.name}
  #Cache config
  redis:
    host: 127.0.0.1
    password: test123
    port: 6379
    database: 7
  #DB config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/h5?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update #none update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database: mysql




