#Log config
logging:
  config: classpath:log4j2.xml

spring:
  aop:
    proxy-target-class: true
  #Cache config
  redis:
    host: redis
    password: test123
    port: 6379
    database: 7
  #DB config
  datasource:
    url: jdbc:mysql://mysql:3306/h5?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: power
    password: modianpower
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update #none update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database: mysql

#Power config
power:
  openssl:
    keyStorePath: classpath:client_keystore.jks
    trustStorePath: classpath:client_truststore.jks
    keyStorePass: 123456

